name: Build and Deploy to CloudHub 2.0 Sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Build Mule Application
        run: mvn -B clean package --file pom.xml

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-artifact
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Built Artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-artifact

      - name: Get Bearer Token
        id: auth
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_PLATFORM_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}
        run: |
          TOKEN=$(curl -s -X POST https://anypoint.mulesoft.com/accounts/login \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"$ANYPOINT_USERNAME\",\"password\":\"$ANYPOINT_PASSWORD\"}" | jq -r '.access_token')
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Get Environment ID
        id: ids
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
        run: |
          echo "Getting environment ID for SANDBOX..."
          
          ENV_RESPONSE=$(curl -s -X GET "https://anypoint.mulesoft.com/accounts/api/organizations/$ORG_ID/environments" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json")
          
          ENV_ID=$(echo "$ENV_RESPONSE" | jq -r '.data[]? | select(.name=="SANDBOX") | .id')
          
          if [ -z "$ENV_ID" ]; then
            ENV_ID=$(echo "$ENV_RESPONSE" | jq -r '.data[]? | select(.name | ascii_upcase == "SANDBOX") | .id')
          fi
          
          if [ -z "$ENV_ID" ]; then
            echo "ERROR: SANDBOX environment not found!"
            echo "Available environments:"
            echo "$ENV_RESPONSE" | jq -r '.data[]? | .name'
            exit 1
          fi
          
          echo "Found Environment ID: $ENV_ID"
          echo "env_id=$ENV_ID" >> $GITHUB_OUTPUT

      - name: List CloudHub 2.0 Targets (Runtime Fabric)
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
          ENV_ID: ${{ steps.ids.outputs.env_id }}
        run: |
          echo "=========================================="
          echo "Getting CloudHub 2.0 targets (Runtime Fabric)..."
          echo "=========================================="
          
          # CloudHub 2.0 uses Runtime Fabric API
          curl -s -X GET "https://anypoint.mulesoft.com/runtimefabric/api/organizations/$ORG_ID/environments/$ENV_ID/targets" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" | jq '.'

      - name: Get Target ID
        id: target
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
          ENV_ID: ${{ steps.ids.outputs.env_id }}
        run: |
          echo "Getting CloudHub 2.0 target..."
          
          TARGET_RESPONSE=$(curl -s -X GET "https://anypoint.mulesoft.com/runtimefabric/api/organizations/$ORG_ID/environments/$ENV_ID/targets" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json")
          
          echo "Targets Response:"
          echo "$TARGET_RESPONSE" | jq '.'
          
          # Get the first CloudHub 2.0 target (provider: MC)
          TARGET_ID=$(echo "$TARGET_RESPONSE" | jq -r '.[] | select(.provider=="MC") | .id' | head -1)
          
          if [ -z "$TARGET_ID" ]; then
            echo "ERROR: No CloudHub 2.0 targets found!"
            echo "Make sure you have a CloudHub 2.0 private space created in Runtime Manager"
            exit 1
          fi
          
          TARGET_NAME=$(echo "$TARGET_RESPONSE" | jq -r ".[] | select(.id==\"$TARGET_ID\") | .name")
          
          echo "Using Target: $TARGET_NAME (ID: $TARGET_ID)"
          echo "target_id=$TARGET_ID" >> $GITHUB_OUTPUT
          echo "target_name=$TARGET_NAME" >> $GITHUB_OUTPUT

      - name: Deploy to CloudHub 2.0
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
          ENV_ID: ${{ steps.ids.outputs.env_id }}
          TARGET_ID: ${{ steps.target.outputs.target_id }}
        run: |
          JAR_FILE=$(ls *.jar | head -1)
          echo "=========================================="
          echo "Deploying: $JAR_FILE"
          echo "Organization: $ORG_ID"
          echo "Environment: $ENV_ID (SANDBOX)"
          echo "Target: $TARGET_ID"
          echo "=========================================="
          
          # CloudHub 2.0 deployment payload
          cat > deployment.json <<EOF
          {
            "name": "git-actions",
            "target": {
              "provider": "MC",
              "targetId": "$TARGET_ID",
              "replicas": 1,
              "deploymentSettings": {
                "resources": {
                  "cpu": {
                    "reserved": "100m",
                    "limit": "1000m"
                  },
                  "memory": {
                    "reserved": "700Mi",
                    "limit": "700Mi"
                  }
                },
                "http": {
                  "inbound": {
                    "publicUrl": ""
                  }
                },
                "generateDefaultPublicUrl": true,
                "clustered": false,
                "updateStrategy": "rolling",
                "forwardSslSession": false,
                "disableAmLogForwarding": false,
                "persistentObjectStore": false,
                "anypoint": {
                  "muleVersion": "4.6.0"
                }
              }
            },
            "application": {
              "desiredState": "STARTED",
              "configuration": {
                "mule.agent.application.properties.service": {}
              }
            }
          }
          EOF
          
          echo "Deployment configuration:"
          cat deployment.json | jq '.'
          
          # Deploy using Runtime Fabric / CloudHub 2.0 API
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            "https://anypoint.mulesoft.com/amc/application-manager/api/v2/organizations/$ORG_ID/environments/$ENV_ID/deployments" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@$JAR_FILE" \
            -F "appInfoJson=@deployment.json;type=application/json")
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo ""
          echo "HTTP Status: $HTTP_CODE"
          echo "Response:"
          echo "$BODY" | jq '.' 2>/dev/null || echo "$BODY"
          
          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "202" ]; then
            echo ""
            echo "=========================================="
            echo "✅ Deployment initiated successfully!"
            echo "=========================================="
          else
            echo ""
            echo "=========================================="
            echo "❌ Deployment failed with status: $HTTP_CODE"
            echo "=========================================="
            exit 1
          fi

      - name: Monitor Deployment
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
          ENV_ID: ${{ steps.ids.outputs.env_id }}
        run: |
          echo "Waiting for deployment to process..."
          sleep 30
          
          echo "=========================================="
          echo "Checking deployment status..."
          echo "=========================================="
          
          # Check deployment status
          curl -s -X GET \
            "https://anypoint.mulesoft.com/amc/application-manager/api/v2/organizations/$ORG_ID/environments/$ENV_ID/deployments" \
            -H "Authorization: Bearer $TOKEN" | jq '.items[] | select(.name=="git-actions")'
          
          echo ""
          echo "=========================================="
          echo "✅ Deployment check complete!"
          echo "Check Runtime Manager for full status"
          echo "=========================================="