name: Build and Deploy to CloudHub 2.0 Sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Build and Deploy to CloudHub 2.0 Shared Space
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_PLATFORM_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}
          BUSINESS_GROUP_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
        run: |
          echo "=========================================="
          echo "Building and Deploying to CloudHub 2.0"
          echo "Target: Shared Space - US East (Ohio)"
          echo "Environment: Sandbox"
          echo "=========================================="
          
          mvn clean deploy -Pcloudhub2-deploy -DmuleDeploy \
            -Danypoint.username="$ANYPOINT_USERNAME" \
            -Danypoint.password="$ANYPOINT_PASSWORD" \
            -Denvironment="Sandbox" \
            -Dtarget="Shared Space" \
            -Dapplication.name="git-actions" \
            -Dbusiness.group.id="$BUSINESS_GROUP_ID" \
            -DskipTests