name: Build and Deploy to CloudHub 2.0 Sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Build Mule Application
        run: mvn -B clean package --file pom.xml

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-artifact
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Built Artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-artifact

      - name: Install Anypoint CLI
        run: |
          npm install -g anypoint-cli-v4

      - name: List Available Targets
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_PLATFORM_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}
          ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
        run: |
          anypoint-cli-v4 conf username "$ANYPOINT_USERNAME"
          anypoint-cli-v4 conf password "$ANYPOINT_PASSWORD"
          anypoint-cli-v4 conf organization "$ANYPOINT_ORG_ID"
          
          echo "=========================================="
          echo "Available targets for SANDBOX environment:"
          echo "=========================================="
          anypoint-cli-v4 runtime-mgr target list --environment "SANDBOX"

      - name: Deploy to CloudHub 2.0
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_PLATFORM_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}
          ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
        run: |
          JAR_FILE=$(ls *.jar | head -1)
          echo "=========================================="
          echo "Deploying: $JAR_FILE"
          echo "Target: Cloudhub-US-East-2"
          echo "Environment: SANDBOX"
          echo "=========================================="
          
          # Deploy to CloudHub 2.0
          anypoint-cli-v4 runtime-mgr cloudhub2-application deploy \
            --target "Cloudhub-US-East-2" \
            --environment "SANDBOX" \
            git-actions \
            "$JAR_FILE" \
            --runtime-version 4.6.0 \
            --replicas 1 \
            --cpu-reserved 0.1 \
            --memory-reserved 0.5
          
          echo ""
          echo "=========================================="
          echo "Deployment completed!"
          echo "=========================================="

      - name: Verify Deployment
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_PLATFORM_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}
          ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
        run: |
          echo "Waiting 15 seconds for deployment to register..."
          sleep 15
          
          echo "=========================================="
          echo "Application Status:"
          echo "=========================================="
          anypoint-cli-v4 runtime-mgr cloudhub2-application describe git-actions --environment "SANDBOX"