name: Build and Deploy to CloudHub 2.0 Sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Build Mule Application
        run: mvn -B clean package --file pom.xml

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-artifact
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Built Artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-artifact

      - name: Get Bearer Token
        id: auth
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_PLATFORM_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}
        run: |
          TOKEN=$(curl -s -X POST https://anypoint.mulesoft.com/accounts/login \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"$ANYPOINT_USERNAME\",\"password\":\"$ANYPOINT_PASSWORD\"}" | jq -r '.access_token')
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: List All Environments
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
        run: |
          echo "=========================================="
          echo "All available environments:"
          echo "=========================================="
          curl -s -X GET "https://anypoint.mulesoft.com/accounts/api/organizations/$ORG_ID/environments" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" | jq '.'

      - name: Get Environment ID
        id: ids
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
        run: |
          echo "Getting environment ID for SANDBOX..."
          
          # Get all environments and search for SANDBOX (case-insensitive)
          ENV_RESPONSE=$(curl -s -X GET "https://anypoint.mulesoft.com/accounts/api/organizations/$ORG_ID/environments" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json")
          
          echo "Environment Response:"
          echo "$ENV_RESPONSE" | jq '.'
          
          # Try exact match first
          ENV_ID=$(echo "$ENV_RESPONSE" | jq -r '.data[]? | select(.name=="SANDBOX") | .id')
          
          # If not found, try case-insensitive
          if [ -z "$ENV_ID" ]; then
            ENV_ID=$(echo "$ENV_RESPONSE" | jq -r '.data[]? | select(.name | ascii_upcase == "SANDBOX") | .id')
          fi
          
          # If still not found, try Production (common default)
          if [ -z "$ENV_ID" ]; then
            echo "SANDBOX not found, checking for Production or Sandbox (different case)..."
            ENV_ID=$(echo "$ENV_RESPONSE" | jq -r '.data[]? | select(.name=="Production" or .name=="Sandbox") | .id' | head -1)
          fi
          
          if [ -z "$ENV_ID" ]; then
            echo "ERROR: Could not find environment!"
            echo "Available environments:"
            echo "$ENV_RESPONSE" | jq -r '.data[]? | .name'
            exit 1
          fi
          
          echo "Found Environment ID: $ENV_ID"
          echo "env_id=$ENV_ID" >> $GITHUB_OUTPUT

      - name: List Available Targets
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
          ENV_ID: ${{ steps.ids.outputs.env_id }}
        run: |
          echo "=========================================="
          echo "Getting CloudHub 2.0 targets for environment: $ENV_ID"
          echo "=========================================="
          
          # Try the CloudHub 2.0 API endpoint
          curl -s -X GET "https://anypoint.mulesoft.com/cloudhub/api/v2/targets" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-ANYPNT-ENV-ID: $ENV_ID" \
            -H "X-ANYPNT-ORG-ID: $ORG_ID" | jq '.'

      - name: Get Target ID
        id: target
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
          ENV_ID: ${{ steps.ids.outputs.env_id }}
        run: |
          echo "Getting target ID..."
          
          TARGET_RESPONSE=$(curl -s -X GET "https://anypoint.mulesoft.com/cloudhub/api/v2/targets" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-ANYPNT-ENV-ID: $ENV_ID" \
            -H "X-ANYPNT-ORG-ID: $ORG_ID")
          
          echo "Targets Response:"
          echo "$TARGET_RESPONSE" | jq '.'
          
          # Get first available target (or filter by name containing Ohio/US-East)
          TARGET_ID=$(echo "$TARGET_RESPONSE" | jq -r '.[0].id // .id // empty')
          
          if [ -z "$TARGET_ID" ]; then
            echo "ERROR: No targets found!"
            exit 1
          fi
          
          echo "Using Target ID: $TARGET_ID"
          echo "target_id=$TARGET_ID" >> $GITHUB_OUTPUT

      - name: Deploy to CloudHub 2.0
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
          ENV_ID: ${{ steps.ids.outputs.env_id }}
          TARGET_ID: ${{ steps.target.outputs.target_id }}
        run: |
          JAR_FILE=$(ls *.jar | head -1)
          echo "=========================================="
          echo "Deploying: $JAR_FILE"
          echo "Organization: $ORG_ID"
          echo "Environment: $ENV_ID"
          echo "Target: $TARGET_ID"
          echo "=========================================="
          
          # Create deployment configuration
          cat > deployment.json <<EOF
          {
            "name": "git-actions",
            "target": {
              "provider": "MC",
              "targetId": "$TARGET_ID",
              "replicas": 1,
              "deploymentSettings": {
                "resources": {
                  "cpu": {
                    "reserved": "100m",
                    "limit": "1000m"
                  },
                  "memory": {
                    "reserved": "700Mi",
                    "limit": "700Mi"
                  }
                },
                "http": {
                  "inbound": {
                    "publicUrl": "git-actions.usa-e2.cloudhub.io"
                  }
                },
                "generateDefaultPublicUrl": true,
                "clustered": false,
                "updateStrategy": "rolling",
                "forwardSslSession": false,
                "disableAmLogForwarding": false,
                "persistentObjectStore": false,
                "anypoint": {
                  "muleVersion": "4.6.0"
                }
              }
            },
            "application": {
              "desiredState": "STARTED",
              "configuration": {},
              "vCores": "0.1"
            }
          }
          EOF
          
          echo "Deployment configuration:"
          cat deployment.json | jq '.'
          
          # Deploy application
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            "https://anypoint.mulesoft.com/cloudhub/api/v2/applications" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-ANYPNT-ENV-ID: $ENV_ID" \
            -H "X-ANYPNT-ORG-ID: $ORG_ID" \
            -F "file=@$JAR_FILE" \
            -F "appInfoJson=@deployment.json")
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "HTTP Status: $HTTP_CODE"
          echo "Response:"
          echo "$BODY" | jq '.' || echo "$BODY"
          
          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "201" ]; then
            echo "=========================================="
            echo "Deployment initiated successfully!"
            echo "=========================================="
          else
            echo "=========================================="
            echo "Deployment failed with status: $HTTP_CODE"
            echo "=========================================="
            exit 1
          fi

      - name: Check Deployment Status
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          ORG_ID: ${{ secrets.ANYPOINT_BUSINESS_GROUP_ID }}
          ENV_ID: ${{ steps.ids.outputs.env_id }}
        run: |
          echo "Waiting 20 seconds for deployment to process..."
          sleep 20
          
          echo "=========================================="
          echo "Application status:"
          echo "=========================================="
          
          curl -s -X GET \
            "https://anypoint.mulesoft.com/cloudhub/api/v2/applications/git-actions" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-ANYPNT-ENV-ID: $ENV_ID" \
            -H "X-ANYPNT-ORG-ID: $ORG_ID" | jq '.' || echo "Application not found yet"